### ISSUE TITLE
Bug: Cannot destructure property 'cursor' of 'result_info' as it is undefined.

### ISSUE THREAD

**Issue by glynnbird** [sagi/workers-kv#29]
Using the very simplest script using this module:

```js
const WorkersKVREST = require('@sagi.io/workers-kv')
const cfAccountId = process.env.CLOUDFLARE_ACCOUNT_ID;
const cfAuthToken = process.env.CLOUDFLARE_AUTH_TOKEN;
const cfEmail = process.env.CLOUDFLARE_EMAIL;
const WorkersKV = new WorkersKVREST({ cfAccountId, cfAuthToken, cfEmail })

const main = async () => {
  const namespaces = await WorkersKV.listNamespaces()
  console.log(namespaces)
}
main()
```

I get the error: 

```
./node_modules/@sagi.io/workers-kv/lib/methods.js:62
      cursor
      ^

TypeError: Cannot destructure property 'cursor' of 'result_info' as it is undefined.
    at Object.listAllKeys (./node_modules/@sagi.io/workers-kv/lib/methods.js:62:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (./test.js:9:19)
```

**Comment by glynnbird** [comment]
Further context: I supplied an invalid auth token so got an error back from Cloudflare, but I supposed the user experience for this library isn't great when that happens!
